name: byaparlekha
description: A new Flutter application.
publish_to: none
version: 1.1.0+5

environment:
  sdk: ^3.5.3

dependencies:
  archive: ^3.6.1
  auto_size_text: ^3.0.0
  collection: ^1.18.0
  country_pickers: ^3.0.1
  device_info_plus: ^11.2.0
  dio: ^5.7.0
  drift: ^2.23.0
  dropdown_search: ^6.0.1
  excel: ^4.0.6
  file_picker: ^8.1.7
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  flutter_svg: ^2.0.16
  get_it: ^8.0.3
  google_sign_in: ^6.2.2
  googleapis: ^13.2.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  material_design_icons_flutter: ^7.0.7296
  nepali_date_picker: ^6.0.1
  nepali_utils: ^3.0.6
  open_filex: ^4.6.0
  package_info_plus: ^8.1.2
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  progress_dialog:
    git:
      url: https://github.com/Rishan99/progress-dialog
      ref: main
  provider: ^6.1.2
  rxdart: ^0.28.0
  shared_preferences: ^2.3.4
  sleek_circular_slider: ^2.0.1
  sqlite3_flutter_libs: ^0.5.28
  table_sticky_headers: ^2.0.5
  toastification: ^2.3.0
  tuple: ^2.0.2
  webview_flutter: ^4.10.0

dev_dependencies:
  build_runner: ^2.4.13
  drift_dev: ^2.23.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/defaults/
    - assets/images/
    - assets/language/
    - fonts/

  fonts:
    - family: FontAwesomeBrands
      fonts:
        - asset: assets/FontAwesome5_Brands.ttf
    - family: FontAwesomeRegular
      fonts:
        - asset: assets/FontAwesome5_Regular.ttf
    - family: FontAwesomeSolid
      fonts:
        - asset: assets/FontAwesome5_Solid.ttf
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
        - asset: fonts/SourceSansPro-Italic.ttf
          style: italic
        - asset: fonts/SourceSansPro-Black.ttf
          weight: 900
        - asset: fonts/SourceSansPro-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/SourceSansPro-Bold.ttf
          weight: 700
        - asset: fonts/SourceSansPro-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/SourceSansPro-ExtraLight.ttf
          weight: 200
        - asset: fonts/SourceSansPro-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/SourceSansPro-Light.ttf
          weight: 300
        - asset: fonts/SourceSansPro-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: fonts/SourceSansPro-SemiBoldItalic.ttf
          weight: 600
          style: italic
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Black.ttf
          weight: 900
        - asset: fonts/Poppins-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-MediumItalic.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: fonts/Poppins-Thin.ttf
          weight: 200
        - asset: fonts/Poppins-ThinItalic.ttf
          style: italic
          weight: 200
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
