//English letter should e in lower case
const Map<String, String> ResourceMap = {
  'nepali language': 'नेपाली भाषा',
  'categories': 'वर्ग',
  'income': 'आम्दानी ',
  'settings': 'सेटिंग्स',
  'expense': 'खर्च',
  'add': 'थप्नुहोस',
  'accounts': 'खाताहरू',
  'current balance': 'हालको ब्यालेन्स',
  'balance': 'ब्यालेन्स',
  'npr': 'रू',
  'new preference has been added': 'नयाँ प्राथमिकता थपिएको छ',
  'no changes has been made': 'कुनै परिवर्तन गरिएको छैन',
  'person': 'व्यक्ति',
  'profile': 'प्रोफाइल',
  'business directory': 'व्यापार निर्देशिका',
  'other': 'अन्य',
  'bank': 'बैंक',
  'cash': 'नगद',
  'account type': 'खाताको किसिम',
  'update': 'हेरफेर गर्नुहोस',
  'delete': 'मेटाउनुहोस',
  'indicators': 'सूचकहरू',
  'delete transaction': 'मेटाउनुहोस ',
  'are you sure to delete this account?': 'के तपाई यो खाता मेटाउन निश्चित हुनुहुन्छ?',
  'budget': 'बजेट',
  'expense projection': 'खर्चको अनुमान',
  'touch to set': 'बजेट राख्न थिच्नुहोस्',
  'touch to update': 'बजेट राख्न थिच्नुहोस्',
  'set budget': 'बजेट तय गर्नुहोस',
  'update budget': 'बजेट संशोधन गर्नुहोस',
  'clear budget': 'बजेट खाली गर्नुहोस',
  'clear  ': 'खाली गर्नुहोस',
  'dashboard': 'गृहपृष्ठ',
  'cumulative cash projection': 'संचयी नगद योजना',
  "cumulative cash position": "संचयी नगद स्थिति",
  'projection vs actual': 'योजना vs वास्तविक',
  'cash & bank balance': 'नगद र बैंक ब्यालेन्स',
  'home': 'गृहपृष्ठ',
  'expense amount': 'खर्च भएको रकम',
  'business income': 'ब्यबसायबाट भएको आय',
  'select your preferences': 'तपाईंको प्राथमिकता छान्नुहोस',
  'enter amount': 'रकम लेख्नुहोस',
  'source of income': 'आयको शिर्षक',
  'expense category': 'खर्चको शिर्षक',
  'cash outflow category': 'नगद बाहिरिने शिर्षक',
  'select seller': 'विक्रेता चयन गर्नुहोस्',
  'select category': 'शिर्षक छान्नुहोस ',
  'date of expense': 'नगद बाहिरिएको मिति',
  'date of income': 'नगद भित्रीएको मिति',
  'add income': 'आम्दानी राख्नुहोस',
  'add expense': 'खर्च राख्नुहोस',
  'sorry, income for current month can only be added!': 'माफ गर्नुहोस, चालु महिनाको मात्र आम्दानी रकम राख्न सकिन्छ!',
  'sorry, expense for current month can only be added!': 'माफ गर्नुहोस, चालु महिनाको मात्र खर्च रकम राख्न सकिन्छ!',
  'select account': 'खाता चुन्नुहोस',
  'choose date': 'मिति रोज्नुहोस',
  'submit': 'स्वीकार गर्नुहोस',
  'description (optional)': 'विवरण (ऐच्छिक)',
  'please select category.': 'कृपया शिर्षक चुन्नुहोस',
  'please select account.': 'कृपया खाता चुन्नुहोस',
  'no transactions': 'कारोबार भएको छैन',
  'login as guest': 'दर्ता नगरी चलाउनुहोस',
  'login': 'लग-इन',
  'register': 'दर्ता गर्नुहोस',
  'don\'t have an account?': 'तपाईंले दर्ता गर्नुभएको छैन?',
  'select your country': 'देश चयन गर्नुहोस',
  'warning': 'चेतावनी',
  'okay': 'ठिक छ',
  'okay    ': 'ठिक छ',
  'cancel': 'बाहिर निस्कनुहोस्',
  'add new': 'नयाँ राख्नुहोस',
  'add new category': 'नयाँ शिर्षक राख्नुहोस',
  'the data will be lost if you remove the app while using it as guest.': 'दर्ता नगरी चलाउनुहुदा, यो एप्प हटाउनुभएको खण्डमा सबै डेटाहरु हराउन सक्छन।',
  'cannot delete! this account is linked with some transactions.': 'हटाउन सकिएन! यो खाता कुनै कारोबारसँग सम्बन्धित छ।',
  'budget is not enough for the transaction. do you really want to add the transaction?': 'यो कारोबारको लागी बजेट रकम अपुग भएको छ। के तपाई साचै यो कारोबार राख्न चाहनुहुन्छ ?',
  'Budget cannot be cleared as it in use.': 'बजेट प्रयोग भैराखेको हुनाले , खाली  गर्न सकिएन।',
  'budget amount is not enough.': 'बजेट रकम पुगेन।',
  'transaction detail': 'कारोबारको विवरण',
  'date: ': 'मिति: ',
  'detail: ': 'विवरण: ',
  'amount: ': 'रकम: ',
  'image: ': 'फोटो: ',
  'transportation fare': 'ढुवानी',
  'date of inflow': 'भित्रीको मिति',
  'date of outflow': 'बाहिरिको मिति',
  "please select atleast one preference": "कृपया कम्तिमा एक प्राथमिकता चयन गर्नुहोस्",
  'more categories': 'थप श्रेणीहरू',
  'category heading': 'शिर्षक शीर्षक',
  'delete category': 'शिर्षक हटाउने',
  'delete account': 'खाता हटाउने',
  'category name': 'शिर्षकको नाम',
  'add cash in': 'नगद भित्रीएने थप्नुहोस्',
  'add cash out': 'नगद बाहिरिने थप्नुहोस्',
  'are you sure you want to delete this category? deleting the category will also clear all the records related to it.':
      ' के तपाई साचै यो शिर्षक हटाउन चाहनुहुन्छ? हटाउनु भएको खण्डमा यो शिर्षकसँग सम्बन्धित सबै कारोबारहरूपनि मेटिने छन।',
  'update income': 'आम्दानी हेरफेर गर्नुहोस',
  'update expense': 'खर्च हेरफेर गर्नुहोस',
  'are you sure you want to delete this category?': 'के तपाई साचै यो कारोबार हटाउन चाहनुहुन्छ?',
  'are you sure you want to delete this account?': 'के तपाईं पक्का यो खाता मेटाउन चाहानुहुन्छ?',
  'are you sure you want to delete this transaction?': 'के तपाईं पक्का यो लेनदेन मेटाउन चाहानुहुन्छ?',
  'cash outflow projection': 'नगद बाहिरिने शिर्षक',
  'cash inflow projection': 'नगद भित्रीने शिर्षक',
  'cash outflow': 'नगद बाहिरिको',
  'cash inflow': 'नगद भित्रीको',
  'cash in': 'नगद भित्रीएको',
  'cash out': 'नगद बाहिरिएको',
  'cash flow projection': "नगद प्रक्षेपण",
  "confirm logout": "लगआउट पुष्टि गर्नुहोस्",
  'gender': 'लिङ्ग',
  "do you want to logout?": "के तपाई लगआउट गर्न चाहनुहुन्छ?",
  'edit': 'बदल्नु्',
  'email address': 'इ-मेल ठेगाना',
  'address': 'ठेगाना',
  'date of birth (b.s)': 'जन्म मिति (बि.स)',
  'date of birth (a.d)': 'जन्म मिति (ई.स)',
  'first name': 'नाम',
  'name': 'नाम',
  'last name': 'थर',
  'category': "क्यटोगरी",
  'chapter': 'च्याप्टर',
  'phone number': 'फोन नम्बर',
  'password': 'पासवर्ड',
  'date of birth': 'जन्म मिति',
  'report': 'रिपोर्ट',
  'choose your language': 'भाषा छान्नुहोस्',
  'nepali': 'नेपाली',
  'english': 'अंग्रेजी',
  'valid phone number must be added to continue': 'अगाडि बढ्नका लागी मान्य फोन नम्बर राख्नुहोस',
  'skip': 'छोड्नुहोस्',
  'add your photo\nhere': 'तपाईंको फोटो यहाँ\nथप्नुहोस्',
  'error, image cannot be uploaded': 'फोटो अपलोड गर्न सकिएन ',
  'save': 'दर्ता गर्नुहोस् ',
  'please restart your app': 'कृपया तपाईको एप्प पुन: सुरु गर्नुहोस्',
  'a.d date picker': 'ई.स मिति रोज्नुहोस',
  'b.s date picker': 'बि.स मिति रोज्नुहोस',
  'male': 'पुरुष',
  'female': 'महिला',
  'create account': 'खाता खोल्नुहोस ',
  'goat': 'बाख्रा पालन',
  'seed': 'वीउ',
  'vegetable': 'सागसब्जी',
  'poultry': 'कुखुरा पालन',
  'enter opening balance': 'सुरुवाती रकम लेख्नुहोस',
  'enter account name': 'खाताको नाम लेख्नुहोस',
  'add account': 'खाता थप्नुहोस',
  'update account': 'खाता संशोधन गर्नुहोस',
  'attention': 'ध्यान दिनुहोस्',
  'permission required.': 'अनुमति आवाश्यक छ।',
  'open app settings': 'अनुमति आवाश्यक छ।',
  'from': 'बाट',
  'to': 'सम्म',
  'search': 'खोजी गर्नुहोस्',
  'export report': 'रिपोर्ट निर्यात गर्नुहोस्',
  'exit  ': 'बाहिरिनु  ',
  'confirm exit': 'निश्चित हुनुहुन्छ?',
  'confirm': 'गर्न चाहान्छु',
  'do you want to exit this application?': 'के तपाईं यस एप्पबाट बाहिर निस्कन चाहनुहुन्छ?',
  'upload your photo': 'फोटो अपलोड गर्नुहोस्',
  'projected': 'योजना',
  'dimiss': 'खारेज गर्नुहोस्',
  'real': 'वास्तविक',
  'backup': 'ब्याकअप',
  'last backup on': 'पछिल्लो ब्याकअप',
  'success': 'सफलता',
  'data has been backup successfully': 'डाटा सफलतापूर्वक ब्याकअप गरिएको छ।',
  'no backup found': 'कुनै ब्याकअप भेटिएन',
  'you have to create account to create backup, please create account and try again.': 'तपाईंले ब्याकअप गर्न खाता सिर्जना गर्नुपर्नेछ, कृपया खाता सिर्जना गर्नुहोस् र पुन: प्रयास गर्नुहोस्।',
  'go to profile': 'प्रोफाइलमा जानुहोस्',
  'monthly surplus/deficit': 'मासिक बचत/घाटा',
  'surplus': 'मासिक बचत',
  'deficit': 'मासिक घाटा',
  'cumulative surplus/deficit': 'संचयी बचत/घाटा',
  'outflow': 'बाहिरिको',
  'inflow': 'भित्रीको',
  'is daily purchase': 'दैनिक खरिद हो',
  'category with same name already exists': 'उही नामको शिर्षक पहिले नै अवस्थित छ',
  'cannot delete! this category is linked with some transactions.': 'हटाउन सकिएन! यो शिर्षक कुनै कारोबारसँग सम्बन्धित छ।',
  'item with same name already exists': 'उही नामको समान पहिले नै अवस्थित छ',
  'customer with same already exists': 'उही नामको ग्राहक पहिले नै अवस्थित छ',
  'transaction doesnt exists': 'कारोबार भेटिएन',
  'error creating backup, please try again': 'कृपया फेरि प्रयास गर्नुहोस्',
  'daily log': 'दैनिक विवरण',
  'is daily sales': 'दैनिक बिक्री छ',
  'item sold to': 'वस्तु बेचियो',
  'item bought from': 'खरिद गरिएको वस्तु',
  'number of items': 'वस्तुहरूको संख्या',
  'select customer': 'ग्राहक चयन गर्नुहोस्',
  'item': 'वस्तु',
  'quantity': 'मात्रा',
  'amount': 'रकम',
  'bill number': 'बिल नम्बर',
  'invoice number': 'इनभ्वाइस नम्बर',
  'add new customer': 'नयाँ ग्राहक थप्नुहोस्',
  'district': 'जिल्ला',
  'dismiss': 'बाहिर निस्कनुहोस्',
  'province': 'प्रदेश',
  'clear filter': 'फिल्टर हटाउनुहोस्',
  'apply filter': 'फिल्टर लागू गर्नुहोस्',
  'logout': 'लग आउट',
  'palika': 'पालिका',
  'ward': 'वार्ड',
  'marital status': 'वैवाहिक स्थिति',
  'mobile number': 'मोबाइल नम्बर',
  'e-mail': 'इ-मेल',
  'education qualification': 'शैक्षिक योग्यता',
  'other education qualification': 'अन्य शैक्षिक योग्यता',
  'remove photo': 'फोटो हटाउनुहोस्',
  'choose gallery image': 'ग्यालरीबाट फोटो छान्नुहोस्',
  'open camera': 'क्यामेरा खोल',
  'more information': 'थप जानकारी',
  'family detail': 'पारिवारिक विवरण',
  'enterprise detail': 'उद्यम विवरण',
  'details related to byaparlekha': 'byaparlekha सँग सम्बन्धित विवरणहरू',
  'error generating excel, please try again': 'कृपया पुन: प्रयास गर्नुहोस्',
  'photo required': 'फोटो आवश्यक छ',
  'expiry date': 'म्याद सकिने मिति',
  'date of birth required': 'जन्म मिति आवश्यक छ',
  'user must be atleast 18 years of old': 'प्रयोगकर्ता कम्तिमा १८ वर्ष पुरा हुनुपर्छ',
  'father\'s name': 'बुवाको नाम',
  'mother\'s name': 'आमाको नाम',
  'restore data': 'डाटा पुनर्स्थापना गर्न चाहनुहुन्छ?',
  'previous backup data for this user exists, all the remaining changes in the app will be lost. do you want to restore your previous data?':
      'यस प्रयोगकर्ताको अघिल्लो ब्याकअप डाटा उपलब्ध छ; एपमा भएका सबै बाँकी परिवर्तनहरू हराउनेछन्। के तपाईं आफ्नो अघिल्लो डाटा पुनर्स्थापना गर्न चाहनुहुन्छ?',
  'which address you want your correspondence to reach?': 'तपाईं आफ्नो पत्राचार कुन ठेगानामा पाउन चहानुहुन्छ ?',
  'are you a member of any other organization? if yes, please specify here': 'के तपाई अरु कुनै संस्थाको सदस्य हुनुहुन्छ ? यदि हो भने, कृपया यहाँ उल्लेख गर्नुहोस्',
  'copy of registration certificate': 'दर्ता प्रमाणपत्रको प्रतिलिपि',
  'please specify here': 'कृपया यहाँ उल्लेख गर्नुहोस्',
  'copy of pan/vat': 'प्यान/भ्याट को प्रतिलिपि',
  'pan/vat number': 'प्यान/भ्याट नम्बर',
  'registration date': 'दर्ता मिति',
  'registration at': 'दर्ता स्थान',
  'registration number': 'दर्ता नं',
  'yearly turnover': 'वार्षिक कारोबार',
  'current assets': 'हालको सम्पत्ति',
  'cv': 'cv',
  'add children': 'बच्चाहरु थप्नुहोस्',
  'copy of citizenship/passport': 'नागरिकता / राहदानी को प्रतिलिपि',
  'website': 'वेबसाइट',
  'copy of tax clerance': 'कर चुक्ताको प्रतिलिपि',
  'name of organization': 'संगठनको नाम',
  'designation': 'पद',
  'how did you come to know about byaparlekha?': 'byaparlekhaको बारेमा तपाईलाई कसरी थाहा भयो ?',
  'why do you want to become a member of byaparlekha?': 'तपाई किन byaparlekhaको सदस्य बन्न चाहनुहुन्छ?',
  'we would like to know how you see yourself contributing to the objectives of byaparlekha': 'byaparlekhaको उद्देश्यहरूमा तपाईंले आफूलाई कसरी योगदान दिनुभएको देख्नुहुन्छ भनेर हामी जान्न चाहन्छौं',
  'please elaborate on your choice(s)': 'कृपया आफ्नो छनोट (हरू) को बारेमा विस्तृत गर्नुहोस्',
  'how much time can you give to byaparlekha activities?': 'तपाईं byaparlekha गतिविधिहरूमा कति समय दिन सक्नुहुन्छ?',
  'what time would you prefer for byaparlekha programs?': 'तपाइँ byaparlekha कार्यक्रमहरूको लागि कुन समय रुचाउनु हुन्छ?',
  'what type of programs would you want in byaparlekha?': 'तपाईं byaparlekha मा कस्तो प्रकारका कार्यक्रमहरू चाहनुहुन्छ?',
  'membership proposed by (existing member)': '(वर्तमान सदस्य) द्वारा प्रस्तावित सदस्यता',
  'spouse\'s name': 'पति/पत्नीको नाम',
  'spouse\'s profession': 'पति/पत्नीको पेशा',
  'spouse\'s company': 'पति/पत्नीको कम्पनी',
  'have childrens?': 'बच्चाहरू छन्?',
  'children detail': 'बच्चाहरुको विवरण',
  'add company': 'कम्पनी थप्नुहोस्',
  'update company': 'कम्पनी अपडेट',
  'enterprise\'s type': 'उद्यमको प्रकार',
  'enterprise\'s scale': 'उद्यमको स्केल',
  'relationship': 'सम्बन्ध',
  'do you want to give additional personal information?': 'तपाईं थप व्यक्तिगत जानकारी दिन चाहनुहुन्छ?',
  'company detail': 'कम्पनी विवरण',
  'books list': 'किताब सूची',
  'change password': 'पासवर्ड परिवर्तन',
  'attach image': 'फोटो राखनुहोस',
  'attach \n image': 'संलग्न गर्नुहोस् \n फोटो',
  'others specify here': 'अरू यहाँ उल्लेख गर्नुहोस्',
  'business related': 'व्यापार सम्बन्धित',
  'general interest': 'सामान्य चासो',
  'membership applied for': 'सदश्यता प्राप्त गर्नु को उदेश्य',
  'educational qualification': 'शैक्षिक योग्यता',
  'member of other organization': 'अन्य संस्थाको सदस्य',
  'member of other organization designation': 'अन्य संगठन पदनाम सदस्य',
  'companies': 'कम्पनीहरु',
  'childrens': 'बच्चाहरू',
  'correspondence to reach': 'पत्राचारको लागि',
  'i came to know about byaparlekha': 'मैले byaparlekha को बारेमा थाहा पाएँ',
  'i want to become member of byaparlekha for': 'मैले byaparlekha को सदस्यता प्राप्त गर्नु को उदेश्य',
  'i can contribute to the objectives of byaparlekha': 'म byaparlekha को उद्देश्यहरूमा योगदान गर्न सक्छु',
  'i can be engaged on byaparlekha activities for': 'म byaparlekha को गतिबिधिहरुम संलग्न गर्नु को उदेश्य',
  'i would like byaparlekha to organize programs that are': 'म byaparlekhaलाई यो-यो कार्यक्रम आयोजन गराउन चाहन्छु',
  'detail on program': 'कार्यक्रमको विवरण',
  'membership proposed by': 'सदश्यता प्रस्ताब गर्ने',
  'tax clearance': 'कर चुक्ता',
  'registration certificate': 'दर्ता प्रमाणपत्र',
  'pan/vat': 'प्यान/भ्याट',
  'citizenship/passport': 'नागरिकता / राहदानी',
  'see more': 'थप हेर्नुहोस्',
  'see less': 'कम हेर्नुहोस्',
  'are you associated to byaparlekha or wean?': 'के तपाई byaparlekha वा WEANसंग सम्बन्धित हुनुहुन्छ?',
  'member has been registered, and waiting for verification. login credentials will be sent to your mobile number.':
      'सदस्यता दर्ता अनुरोध प्रमाणीकरणको निम्ती पेश गरिएको छ । प्रमाणित पस्चात लग इन विवरणहरू तपाईंको फोनमा पठाइनेछ।',
  'address of correspondence to reach': 'पत्राचारको ठेगाना',
  'select chapter position': 'Chapterको लागि पद छान्नुहोस्',
  'select byaparlekha position': 'byaparlekhaको लागि पद छान्नुहोस्',
  'is member of byaparlekha or byaparlekha chapter?': 'byaparlekha वा byaparlekha Chapter को सदस्य हो?',
  'one or more field is remaining': 'एक वा बढी क्षेत्र बाँकी छ',
  'error': 'त्रुटि भयो',
  'less information': 'कम जानकारी',
  "projection vs actual cash flow": "योजना vs वास्तविक नगद भित्रीको/बाहिरिको",
  "cash flow source heading": "नगद भित्रीको/बाहिरिको स्रोत शीर्षक",
  "projected cash flow": "प्रक्षेपित नगद भित्रीको/बाहिरिको",
  "actual cash flow": "वास्तविक नगद भित्रीको/बाहिरिको",
  "business cash inflow": "व्यापार नगद भित्रीको",
  "cash outflow amount": "नगद बाहिरिको रकम",
  "source of cash outflow": "नगद बाहिरिको स्रोत",
  "source of cash inflow": "नगद भित्रीको स्रोत",
  "add cash inflow": "नगद भित्रीको थप्नुहोस्",
  "add cash outflow": "नगद बाहिरिको थप्नुहोस्"
};
